### ISSUE TITLE
Missed solutions

### ISSUE THREAD

**Issue by Victorlouisdg** [Victorlouisdg/ur-analytic-ik#4]
Pose that seems very reachable, but no IK solutions are returned.

![image](https://github.com/Victorlouisdg/ur-analytic-ik/assets/23340946/a9251c40-f16e-41da-b14c-8c4127a765d7)

**Comment by Victorlouisdg** [comment]
Even weirder: when I build the transform myself, I get 8 solutions as expected:
![image](https://github.com/Victorlouisdg/ur-analytic-ik/assets/23340946/95712220-1a4b-40b9-81b5-7a364640b768)

**Comment by Victorlouisdg** [comment]
The difference is that there are two values that differ that are very close to 0.
![image](https://github.com/Victorlouisdg/ur-analytic-ik/assets/23340946/fa6629c3-30af-4eb9-908d-74273c272b7e)

**Comment by Victorlouisdg** [comment]
```python
np.ascontiguousarray(transform_numpy_4x4)
```
Solves the issue in this case.

**Comment by Victorlouisdg** [comment]
I believe this `memcpy` causes the problem because the received matrix is not guaranteed to be row-major.
![image](https://github.com/Victorlouisdg/ur-analytic-ik/assets/23340946/39c7ce07-23eb-40e4-87db-2c50347704f8)

**Comment by tlpss** [comment]
same issue:
```
x_axis = np.array([-1.0,0,0,0])
y_axis = np.array([0,1,0,0])
z_axis = np.array([0,0,-1.0,0])
position = np.array([0.5,0,-0.01,1])

tcp_target_pose = np.array([x_axis, y_axis, z_axis, position]).T
tcp_target_pose = np.ascontiguousarray(tcp_target_pose)

joints = ur3e.inverse_kinematics(tcp_target_pose)
print(joints)
```
Does not work w/o explicitly making the array contiguous. 

possible solution: https://nanobind.readthedocs.io/en/latest/ndarray.html#overview
