### ISSUE TITLE
Solutions include (slightly) incorrect solutions for specific joint angles

### ISSUE THREAD

**Issue by Victorlouisdg** [Victorlouisdg/ur-analytic-ik#5]
After multiple reports, I've finally been able to reproduce this problem.

There is a test to check the correctness of all the returned IK solutions i.e. `test_correctness()`, which tests:
```python
FK(random_joints) == FK(IK(FK(random_joints)))
```
 for 10000 `random_joints`. I have also never noticed any problems when doing IK with the TCP poses from the real robots. However a problem occurs when users use specific, nice, round joint angles such as:
```python
joints = np.deg2rad([0, -45, -90, -90, 90, 0])
```
This triggers an incorrectly handled edge case in the IK calculations. This seems to manifest (only?) as additional incorrect joint solutions being included. What is striking however is that these solutions are only *slighty* incorrect, i.e. the TCP pose is translated a few cm or rotated a few degrees.

There are two fixes possible:
* **Easy fix:** run FK on all IK solutions and remove incorrect ones, this won't increase runtime significantly as IK is cheap. 
* **Best fix:** correctly handle the edge cases, but this required some digging.

For now, I'll implement the **easy fix** and add a test case for these specific angles.

**Comment by Victorlouisdg** [comment]
Easy fix implementen in: https://github.com/Victorlouisdg/ur-analytic-ik/commit/0c7a8cc7a16e8aef03bdc8c5683954be724a2dc8

**Comment by tlpss** [comment]
@adverley, I think this one solves all your problems?

**Comment by adverley** [comment]
Let's close it for now, I won't have any opportunities to test this the
next two months.

Thanks for the update!
